### ISSUE TITLE
[melodic] Robot model not visible on Rviz using fake node 

### ISSUE THREAD

**Issue by virgileTN** [ROBOTIS-GIT/turtlebot3#376]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?
    - [x] I'm Trying to simulate them.
    - [x] Burger
    - [x] Waffle
    - [x] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?
    - [x] None cf: 1
    - [ ] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?
    - [x] None cf: 1
    - [ ] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

4. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [x] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: [1.14.3]  (melodic)
    - Firmware version: [x.x.x]

6. Write down the commands you used in order
### To install for melodic from sources

I'm using this script :
```
mkdir -p ~/catkin_ws/src/
cd ~/catkin_ws/src/
git clone https://github.com/ROBOTIS-GIT/turtlebot3.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_applications_msgs.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_applications.git
git clone https://github.com/ROBOTIS-GIT/turtlebot3_autorace.git
git clone https://github.com/ROBOTIS-GIT/turtlebot3_deliver.git
cd ~/catkin_ws/

sudo apt install ros-melodic-joy ros-melodic-teleop-twist-joy \
                 ros-melodic-teleop-twist-keyboard ros-melodic-laser-proc \
                 ros-melodic-rgbd-launch ros-melodic-depthimage-to-laserscan \
                 ros-melodic-rosserial-arduino ros-melodic-rosserial-python \
                 ros-melodic-rosserial-server ros-melodic-rosserial-client \
                 ros-melodic-rosserial-msgs ros-melodic-amcl \
                 ros-melodic-map-server ros-melodic-move-base \
                 ros-melodic-urdf ros-melodic-xacro \
                 ros-melodic-compressed-image-transport \
                 ros-melodic-rqt-image-view ros-melodic-gmapping \
                 ros-melodic-navigation ros-melodic-interactive-markers
# Result :
# E: Unable to locate package ros-melodic-teleop-twist-joy
# E: Unable to locate package ros-melodic-depthimage-to-laserscan
# E: Unable to locate package ros-melodic-gmapping

rosdep install --from-paths src --ignore-src -r -y
# Result :
# ERROR: the following packages/stacks could not have their rosdep keys resolved
# to system dependencies:
# turtlebot3_slam: Cannot locate rosdep definition for [gmapping]
# Continuing to install resolvable dependencies...
# All required rosdeps installed successfully

# Intall cartographer from ros binaries
sudo apt install ros-melodic-cartographer ros-melodic-cartographer-ros ros-melodic-cartographer-ros-msgs ros-melodic-cartographer-rviz
catkin_make

```
not found packages :
 - Gmapping => i'm planning to use cartographer anyway.
 - ros-melodic-teleop-twist-joy => i'm not planning to control it with joystick.
 - ros-melodic-depthimage-to-laserscan => I'm planning to use burger

 ### tests :
 #### Fake node
 I'm trying to simulate with fake node according to :
 http://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#turtlebot3-simulation-using-fake-node

 ##### Burger
 Terminal 1 :
 ```
 export TURTLEBOT3_MODEL=burger
 roslaunch turtlebot3_fake turtlebot3_fake.launch
 ```
 Terminal 2 :
 ```
 export TURTLEBOT3_MODEL=burger
 roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch
 ```

**Results**
The robot model is not visible, but i can teleop the robot
![rviz](https://user-images.githubusercontent.com/6124823/51401805-0103c700-1b4c-11e9-9f6a-b405825ecdfc.png)
  ##### Waffle
 Terminal 1 :
 ```
 export TURTLEBOT3_MODEL=waffle
 roslaunch turtlebot3_fake turtlebot3_fake.launch
 ```
 Terminal 2 :
 ```
 export TURTLEBOT3_MODEL=waffle
 roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch
 ```

**Results**
The model is... definitively not the expected one ;). And I can't teleop it. 
![waffle_rviz](https://user-images.githubusercontent.com/6124823/51401781-f9dcb900-1b4b-11e9-876e-18d079d8648e.png)

#### Gazebo
Terminal 1 :
```
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
```

7. Copy and Paste your error message on terminal

```
virgile@Leon:~/catkin_ws$ roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch
... logging to /home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/roslaunch-Leon-29954.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://Leon:35913/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [29967]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f
process[rosout-1]: started with pid [29978]
started core service [/rosout]
process[gazebo-2]: started with pid [29984]
process[gazebo_gui-3]: started with pid [29989]
process[spawn_urdf-4]: started with pid [29995]
[ INFO] [1547830461.817209739]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1547830461.824400081]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1547830461.853749754]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1547830461.865668517]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 31, in <module>
    from tf.transformations import quaternion_from_euler
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 31, in <module>
    from .listener import Transformer, TransformListener, TransformerROS
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/listener.py", line 29, in <module>
    import numpy
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
Warning [parser.cc:950] XML Element[scene], child of element[sdf] not defined in SDF. Ignoring[scene]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
[spawn_urdf-4] process has died [pid 29995, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -model turtlebot3_burger -x 0.0 -y 0.0 -z 0.0 -param robot_description __name:=spawn_urdf __log:=/home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/spawn_urdf-4.log].
log file: /home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/spawn_urdf-4*.log
[ INFO] [1547830462.483451793, 0.023000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1547830462.530468309, 0.065000000]: Physics dynamic reconfigure ready.
```

8. Please, describe detailedly what difficulty you are in

    - The problem seems to be linked somehow with the model of the robot. as stated in :

```
[spawn_urdf-4] process has died [pid 29995, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -model turtlebot3_burger -x 0.0 -y 0.0 -z 0.0 -param robot_description __name:=spawn_urdf __log:=/home/virgile/.ros/log/b2f6a3e8-1b41-11e9-8b2a-2816adda9a3f/spawn_urdf-4.log].
```

  - Another clue is a problem in the SDF file but it should **only concern Gazebo** right ?
```
Warning [parser.cc:950] XML Element[scene], child of element[sdf] not defined in SDF. Ignoring[scene]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
```

  - There may be a problem in one model is causing the following error of quaternion conversion. Quaternions must be normed, if not that can create conversions error. A not defined quaternion aka (0,0,0,0) can lead to the following error ?

```
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/gazebo_ros/spawn_model", line 31, in <module>
    from tf.transformations import quaternion_from_euler
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 31, in <module>
    from .listener import Transformer, TransformListener, TransformerROS
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/listener.py", line 29, in <module>
    import numpy
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/virgile/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```

Thanks for your help and beautiful work :)

**Comment by virgileTN** [comment]
I solved the numpy problem, by uninstalling numpy with pip `pip uninstall numpy` (it was both installed by apt and pip). 

Currently, the gazebo sim is working fine with karto slam. But I'm still unable to see the model in fake node.

**Comment by kijongGil** [comment]
I'm so sorry for late reply.
We will release soon ROS Melodic version with turtlebot3.
You will be able to work with Melodic. 

Thanks,
Gilbert.

**Comment by virgileTN** [comment]
Don't worry, I successfully installed and runned it on several computers with a simple install script: 
```
mkdir -p ~/catkin_ws/src/
slam_turtlebot3_dir=$PWD
cd ~/catkin_ws/src/
if [ "`grep CATKIN_WS_DIR ~/.bashrc`" == "" ]
then
  echo 'export CATKIN_WS_DIR=~/catkin_ws' >> ~/.bashrc
  source ~/.bashrc
fi
if [ "`grep TURTLEBOT3_MODEL ~/.bashrc`" == "" ]
then
  echo 'export TURTLEBOT3_MODEL=burger' >> ~/.bashrc
  source ~/.bashrc
fi

git clone https://github.com/ROBOTIS-GIT/turtlebot3.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_applications_msgs.git --branch melodic-devel
git clone https://github.com/ROBOTIS-GIT/turtlebot3_applications.git
git clone https://github.com/ROBOTIS-GIT/turtlebot3_autorace.git
git clone https://github.com/ROBOTIS-GIT/turtlebot3_deliver.git

cd ~/catkin_ws/
# Install required packages
sudo apt install ros-melodic-joy \
                 ros-melodic-teleop-twist-keyboard \
                 ros-melodic-laser-proc \
                 ros-melodic-rgbd-launch \
                 ros-melodic-rosserial-arduino \
                 ros-melodic-rosserial-python \
                 ros-melodic-rosserial-server \
                 ros-melodic-rosserial-client \
                 ros-melodic-rosserial-msgs \
                 ros-melodic-amcl \
                 ros-melodic-map-server \
                 ros-melodic-move-base \
                 ros-melodic-urdf \
                 ros-melodic-xacro \
                 ros-melodic-compressed-image-transport \
                 ros-melodic-rqt-image-view \
                 ros-melodic-navigation \
                 ros-melodic-interactive-markers \
                 ros-melodic-slam-karto \
                 ros-melodic-cartographer \
                 ros-melodic-cartographer-ros \
                 ros-melodic-cartographer-ros-msgs \
                 ros-melodic-cartographer-rviz

# Install potentially missing dependencies
rosdep install --from-paths src --ignore-src -r -y

# Build the whole catkin workspace
catkin_make
```
It wasn't working because of new TF conventions in melodic where _/_ were suppressed to avoid confusion with topic names. So to make it work in melodic I just changed frames names removing slashes in `global_costmap_params.yaml` and `local_costmap_params.yaml` config files.

For example the new global_costmap_params.yaml is the following
```
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
```
